### ISSUE TITLE
Provide both unit tests and integration tests

### ISSUE THREAD

**Issue by holly-cummins** [aromerohcr/ibm-bluepages-js#7]
At the moment, all of the tests depend on access to a live bluepages server. This means development can't be done offline or outside the VPN, and running the tests is a bit slow. As the number of tests increases, this is more of an issue. 

I'd suggest that some integration testing against the live server is good, but not all tests need to run that way. It might be a good idea to have both unit tests and a small number of integration tests. The integration tests would be run with their own mode and would talk to the real server, and the unit tests would talk to a mock. I like nock.js; you can use `nock record` to interrogate the logic of the calls, but then take the recorded inputs and outputs and use them to build a mock in code. Then most tests can use just the mock. (This blog is a good intro to nock.js)

**Comment by aromerohcr** [comment]
Hi Holly, thanks for bringing this one up! 
We have just separated the integration tests from unit tests using Nock (thanks for the advise!).

We added some dummy data for the Unit tests, now you can run both tests separate either using the `npm run test:int` or `npm run test:unit` commands, unit testing will not longer need VPN which will make them run faster.

We'll keep it this way in the meantime until we have time to work on more elaborated tests using `nock record`. Please let me know if they get the work done as expected.

Thanks.

**Comment by holly-cummins** [comment]
Super!
